### PR TITLE
fixing http/s proxy handling for openshift provider

### LINKED ISSUE #71: Support http_proxy env variable
Authentication fails if the openshift cluster's public endpoint is reachable only through an http proxy.

Error message on my environment: 
> 018/05/28 07:44:32 oauthproxy.go:582: error redeeming code (client:10.128.4.1:33746 ("10.0.1.152")): Post https://openshift_public_url/oauth/token:  dial tcp xx.xx.xx.xx:443: getsockopt: connection timed out
2018/05/28 07:44:32 oauthproxy.go:399: ErrorPage 500 Internal Error Internal Error

I tried configuring uppercase and lowercase environment variables http_proxy & https_proxy but it doesn't work. I looked at the authproxy.go source code and proxy handling doesn't seem implemented.

This is a real show stopper for us because we would like to expose [Prometheus](https://docs.openshift.com/container-platform/3.9/install_config/cluster_metrics.html#openshift-prometheus) dashboards to users coming from Internet and our openshift cluster can't be directly exposed on Internet.

### PR DESCRIPTION
**Pull request by patlachance**
Fixes #71

### CODE REVIEW

File: providers/openshift/provider.go [hunk 1]
```diff
@@ -144,6 +144,7 @@ func (p *OpenShiftProvider) setCA(paths []string) error {
 		return err
 	}
 	p.Client.Transport = &http.Transport{
+		Proxy: http.ProxyFromEnvironment,
```
Comment (mrogers950) [inline providers/openshift/provider.go]: We should modify the transport for this outside of the setCA function.

**Comment by brancz** [comment]
@openshift/sig-auth

File: providers/openshift/provider.go (hunk 1 above)
Comment (patlachance) [reply providers/openshift/provider.go]: http_proxy and https_proxy environment variables are handled by [http.DefaultTransport](https://golang.org/src/net/http/transport.go). This function is used to set custom CA on the transport but IMO it shouldn't discard other http.DefaultTransport default properties. But this is what is does since we need to change it later so it handle proxy env variables again.

I couldn't find a way to extend the p.client.transport outside this function without having to define the custom CA as well in the new function. 

Any idea how to do it?

**Comment by patlachance** [comment]
@mrogers950 please see comment on your review. Don't know how to do it without managing custom CA at the same time.

**Comment by mrogers950** [comment]
@patlachance sorry for the delay, I see what you're saying about setting the transport here. If you can also change the function name to setCAandTransportProxy or similar, that would be acceptable, just to make it clear that the function is doing both of these things.

**Comment by patlachance** [comment]
@mrogers950 ok I’ll do it over the weekend.

**Comment by mrogers950** [comment]
@patlachance I'm still waiting on your fixup. I'd be willing to open a separate PR and push the fix through myself if you have not had the time to return to this, just let me know.

**Comment by patlachance** [comment]
@mrogers950 sorry for the delay. Done now!

**Comment by mrogers950** [comment]
@patlachance looks good, thank you for your contribution!
/lgtm
